{{- if .Values.env }}
{{- $hasValues := false }}
{{- range $k, $v := .Values.env }}
  {{- if $v }}{{ $hasValues = true }}{{ end }}
{{- end }}
{{- if $hasValues }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autoanneal.fullname" . }}-config
  labels:
    {{- include "autoanneal.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
