{{- if not .Values.job.enabled }}
{{- range .Values.repos }}
{{- if .schedule }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "autoanneal.fullname" $ }}-{{ .name }}
  labels:
    {{- include "autoanneal.labels" $ | nindent 4 }}
    autoanneal/repo: {{ .name }}
spec:
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: {{ $.Values.cronJob.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $.Values.cronJob.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $.Values.cronJob.successfulJobsHistoryLimit }}
  startingDeadlineSeconds: {{ $.Values.cronJob.startingDeadlineSeconds }}
  suspend: {{ $.Values.cronJob.suspend }}
  jobTemplate:
    metadata:
      labels:
        {{- include "autoanneal.labels" $ | nindent 8 }}
        autoanneal/repo: {{ .name }}
      {{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      backoffLimit: {{ $.Values.cronJob.backoffLimit }}
      activeDeadlineSeconds: {{ $.Values.cronJob.activeDeadlineSeconds }}
      ttlSecondsAfterFinished: {{ $.Values.cronJob.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            {{- include "autoanneal.selectorLabels" $ | nindent 12 }}
            autoanneal/repo: {{ .name }}
          {{- with $.Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- include "autoanneal.podSpec" (dict "repo" . "root" $) | nindent 10 }}
{{- end }}
{{- end }}
{{- end }}
